import { projects, formatFCFA, formatNumber } from '@/lib/data';
import { Search, Filter, Plus, MoreHorizontal, CheckCircle2, Clock, AlertCircle, FileText, Download, Users, Wallet, Briefcase, Settings, Activity, ShieldCheck, TrendingUp } from 'lucide-react';

function PageTitle({ title, subtitle, action }: { title: string; subtitle: string; action?: string }) {
  return <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="font-display font-bold text-2xl text-slate-900">{title}</h1><p className="text-sm text-slate-500 mt-1">{subtitle}</p></div>{action && <button className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-slate-900 text-white text-sm font-semibold hover:bg-slate-800"><Plus className="w-4 h-4" />{action}</button>}</div>;
}
const TableTools = () => <div className="flex flex-col sm:flex-row gap-3 mb-4"><div className="flex-1 relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><input placeholder="Rechercher..." className="w-full pl-10 pr-4 py-2.5 rounded-lg border border-slate-200 outline-none text-sm focus:border-slate-500" /></div><button className="flex items-center gap-2 px-4 py-2.5 rounded-lg border border-slate-200 text-sm font-medium"><Filter className="w-4 h-4" /> Filtrer</button></div>;
const Status = ({ kind }: { kind: 'active' | 'pending' | 'draft' }) => kind === 'active' ? <span className="px-2 py-1 rounded-full bg-emerald-50 text-emerald-600 text-xs font-medium">Actif</span> : kind === 'pending' ? <span className="px-2 py-1 rounded-full bg-amber-50 text-amber-600 text-xs font-medium">En attente</span> : <span className="px-2 py-1 rounded-full bg-slate-100 text-slate-600 text-xs font-medium">Brouillon</span>;

export function AdminDashboard() { const stats = [{ l:'Investisseurs',v:'124',i:Users },{ l:'Actions émises',v:'8 450',i:TrendingUp },{ l:'Souscriptions',v:'86 000 000 FCFA',i:Wallet },{ l:'Projets actifs',v:'3',i:Briefcase }]; return <div className="space-y-6"><div className="rounded-2xl bg-gradient-to-br from-slate-900 to-slate-700 text-white p-6 sm:p-8"><h2 className="font-display font-bold text-2xl">Vue d'ensemble de la plateforme</h2><p className="text-slate-300 text-sm mt-1">Pilotez vos projets, investisseurs et opérations depuis cet espace.</p></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{stats.map(s=><div key={s.l} className="bg-white rounded-xl p-5 border border-slate-100"><div className="w-10 h-10 rounded-lg bg-slate-100 text-slate-700 flex items-center justify-center mb-3"><s.i className="w-5 h-5" /></div><div className="text-xl font-display font-bold text-slate-900">{s.v}</div><div className="text-xs text-slate-500 mt-1">{s.l}</div></div>)}</div><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><div className="bg-white rounded-2xl p-6 border border-slate-100"><h3 className="font-display font-bold text-lg mb-4">Répartition des actions</h3><div className="flex items-center gap-8"><div className="w-36 h-36 rounded-full bg-[conic-gradient(#334155_0_50%,#d97706_50%_100%)] p-7"><div className="w-full h-full rounded-full bg-white flex items-center justify-center"><span className="text-xs text-slate-500 text-center">30 000<br/><b className="text-slate-900">actions</b></span></div></div><div className="space-y-3 text-sm"><div className="flex items-center gap-2"><span className="w-3 h-3 rounded-full bg-slate-700" /> KF Business <b>50%</b></div><div className="flex items-center gap-2"><span className="w-3 h-3 rounded-full bg-gold-600" /> Investisseurs <b>50%</b></div></div></div></div><div className="bg-white rounded-2xl p-6 border border-slate-100"><h3 className="font-display font-bold text-lg mb-4">Alertes à traiter</h3>{['8 paiements en attente','12 dossiers KYC à valider','3 rapports à publier'].map((x,i)=><div key={x} className="flex items-center gap-3 p-3 rounded-lg bg-slate-50 mb-2"><AlertCircle className="w-4 h-4 text-amber-500" /><span className="text-sm text-slate-700 flex-1">{x}</span><button className="text-xs font-medium text-slate-600">Voir</button></div>)}</div></div></div>; }

export function AdminProjects() { return <div className="space-y-6"><PageTitle title="Gestion des projets" subtitle="Créez, modifiez et publiez les projets d'investissement." action="Nouveau projet" /><div className="bg-white rounded-2xl p-6 border border-slate-100"><TableTools /><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500 uppercase"><tr><th className="text-left px-4 py-3">Projet</th><th className="text-left px-4 py-3">Secteur</th><th className="text-right px-4 py-3">Budget</th><th className="text-right px-4 py-3">Actions</th><th className="text-center px-4 py-3">Statut</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{projects.map((p,i)=><tr key={p.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-medium text-slate-900">{p.name}</td><td className="px-4 py-3 text-slate-600">{p.sector}</td><td className="px-4 py-3 text-right">{formatFCFA(p.budget)}</td><td className="px-4 py-3 text-right">{formatNumber(p.sharesTotal)}</td><td className="px-4 py-3 text-center"><Status kind={i===0?'active':'draft'} /></td><td className="px-4 py-3 text-right"><MoreHorizontal className="w-4 h-4 text-slate-400 ml-auto" /></td></tr>)}</tbody></table></div></div></div>; }

export function AdminInvestors() { return <div className="space-y-6"><PageTitle title="Gestion des investisseurs" subtitle="Consultez les profils, investissements et statuts KYC." /><div className="bg-white rounded-2xl p-6 border border-slate-100"><TableTools /><SimpleInvestorTable /></div></div>; }
function SimpleInvestorTable(){ return <table className="w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500 uppercase"><tr><th className="text-left px-4 py-3">Investisseur</th><th className="text-left px-4 py-3">Email</th><th className="text-right px-4 py-3">Investi</th><th className="text-center px-4 py-3">KYC</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{[['Awa Diop','awa@email.sn',1000000,true],['Moussa Sarr','moussa@email.sn',5000000,true],['Fatou Ndiaye','fatou@email.sn',500000,false],['Khadi Fall','khadi@email.sn',100000,true]].map((r)=><tr key={r[1] as string} className="hover:bg-slate-50"><td className="px-4 py-3 font-medium">{r[0] as string}</td><td className="px-4 py-3 text-slate-600">{r[1] as string}</td><td className="px-4 py-3 text-right">{formatFCFA(r[2] as number)}</td><td className="px-4 py-3 text-center">{r[3] ? <Status kind="active" /> : <Status kind="pending" />}</td><td className="px-4 py-3 text-right"><MoreHorizontal className="w-4 h-4 text-slate-400 ml-auto" /></td></tr>)}</tbody></table>; }

export function AdminVerifications(){ return <div className="space-y-6"><PageTitle title="Validation des dossiers" subtitle="Validez les pièces d'identité et les profils investisseurs." /><div className="bg-white rounded-2xl p-6 border border-slate-100"><TableTools /><div className="space-y-3">{['Fatou Ndiaye','Mamadou Ba','Sokhna Fall'].map((n)=><div key={n} className="flex items-center gap-3 p-4 rounded-xl border border-slate-100"><div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center text-sm font-bold text-slate-600">{n[0]}</div><div className="flex-1"><div className="font-medium text-slate-900">{n}</div><div className="text-xs text-slate-500">CNI • justificatif de domicile • reçu le 22/09/2026</div></div><button className="px-3 py-2 rounded-lg bg-slate-900 text-white text-xs font-medium">Examiner</button></div>)}</div></div></div>; }

function GenericTable({ title, subtitle, amount }: { title: string; subtitle: string; amount: string }) { return <div className="space-y-6"><PageTitle title={title} subtitle={subtitle} /><div className="bg-white rounded-2xl p-6 border border-slate-100"><TableTools /><div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-5"><div className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-500">Volume total</div><div className="font-display font-bold text-xl text-slate-900 mt-1">{amount}</div></div><div className="rounded-xl bg-emerald-50 p-4"><div className="text-xs text-emerald-700">Validés</div><div className="font-display font-bold text-xl text-emerald-700 mt-1">68</div></div><div className="rounded-xl bg-amber-50 p-4"><div className="text-xs text-amber-700">En attente</div><div className="font-display font-bold text-xl text-amber-700 mt-1">8</div></div></div><div className="space-y-3">{['Ferme Avicole 5 000 Pondeuses','Mini-Boulangerie Dakar','Culture Maraîchère'].map((p,i)=><div key={p} className="flex items-center gap-3 p-4 rounded-lg border border-slate-100"><div className="flex-1"><div className="font-medium text-slate-900 text-sm">{p}</div><div className="text-xs text-slate-500">Dernière mise à jour : 22/09/2026</div></div><Status kind={i===1?'pending':'active'} /><MoreHorizontal className="w-4 h-4 text-slate-400" /></div>)}</div></div></div>; }
export function AdminSubscriptions(){return <GenericTable title="Suivi des souscriptions" subtitle="Toutes les souscriptions par projet et par investisseur." amount="86 000 000 FCFA" />}
export function AdminPayments(){return <GenericTable title="Suivi des paiements" subtitle="Validez et contrôlez les flux financiers." amount="125 000 000 FCFA" />}
export function AdminShares(){return <GenericTable title="Gestion des actions" subtitle="Suivez les actions disponibles, réservées et souscrites." amount="8 450 / 30 000" />}
export function AdminDocuments(){return <GenericTable title="Gestion des documents" subtitle="Publiez les contrats, business plans et rapports." amount="42 documents" />}
export function AdminReports(){return <GenericTable title="Rapports financiers" subtitle="Publiez les résultats et rapports aux investisseurs." amount="12 rapports" />}
export function AdminExports(){return <div className="space-y-6"><PageTitle title="Exportations" subtitle="Exportez les données comptables et investisseurs." /><div className="grid md:grid-cols-2 gap-4">{['Export investisseurs','Export souscriptions','Export paiements','Export comptable'].map(x=><div key={x} className="bg-white rounded-2xl p-6 border border-slate-100 flex items-center gap-4"><Download className="w-6 h-6 text-slate-600" /><div className="flex-1 font-medium text-slate-900">{x}</div><button className="px-3 py-2 rounded-lg bg-slate-900 text-white text-xs">Télécharger</button></div>)}</div></div>}
export function AdminLogs(){return <div className="space-y-6"><PageTitle title="Journal des opérations" subtitle="Historique des actions effectuées sur la plateforme." /><div className="bg-white rounded-2xl p-6 border border-slate-100 space-y-3">{['Validation KYC — Awa Diop','Publication du rapport Q3 2026','Modification du projet avicole','Export investisseurs généré'].map((x,i)=><div key={x} className="flex items-center gap-3 border-b border-slate-100 pb-3"><Activity className="w-4 h-4 text-slate-500" /><div className="flex-1 text-sm text-slate-700">{x}</div><span className="text-xs text-slate-400">22/09/2026 • 14:{20+i} </span></div>)}</div></div>}
export function AdminSettings(){return <div className="space-y-6"><PageTitle title="Paramètres & accès" subtitle="Gérez les rôles, les accès et les paramètres système." /><div className="grid md:grid-cols-2 gap-6"><div className="bg-white rounded-2xl p-6 border border-slate-100"><Settings className="w-6 h-6 text-slate-700 mb-3" /><h3 className="font-display font-bold text-lg">Rôles et permissions</h3><p className="text-sm text-slate-500 mt-2">Administrateur, comptable et investisseur avec accès adaptés.</p><button className="mt-4 px-4 py-2 rounded-lg bg-slate-900 text-white text-sm">Gérer les accès</button></div><div className="bg-white rounded-2xl p-6 border border-slate-100"><ShieldCheck className="w-6 h-6 text-emerald-600 mb-3" /><h3 className="font-display font-bold text-lg">Sécurité</h3><p className="text-sm text-slate-500 mt-2">Double authentification, sauvegardes et journalisation activées.</p><button className="mt-4 px-4 py-2 rounded-lg bg-slate-100 text-slate-700 text-sm">Configurer</button></div></div></div>}
